// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Destination struct {
	ID        uuid.UUID
	MessageID uuid.UUID
	Receiver  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID        uuid.UUID
	Service   string
	Title     string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
